name: Rust CI

on:
  push:
    branches:
      - 'master'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [1.85.0]

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy
    - run: cargo fmt --all -- --check
    - run: cargo clippy -- -D warnings
    - run: cargo test --verbose
